using System;using System.IO;using System.Text;using System.Drawing;using System.Drawing.Drawing2D;using System.Windows.Forms;using System.Collections.Generic;using System.Runtime.InteropServices;
static class Engine {
 const string DLL="engine.dll";
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern void st_init();
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern void st_tick(ushort key);
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern ushort st_page();
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern ushort st_save_bytes();
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern ushort st_vp(ushort vp);
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern ushort st_requests();
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern void st_saved(int ok,ushort seq);
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern void st_save([Out]byte[] b,ushort seq);
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern int st_valid(byte[] b);
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern int st_load(byte[] b);
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern void st_preferences(byte[] b);
 [DllImport(DLL,CallingConvention=CallingConvention.Cdecl)] public static extern ushort st_audio(int playing);
}
sealed class Item { public bool Key;public int Page,X,Y,W,H,Min,Max,Lib;public ushort VP,Code; }
sealed class Preview:Form {
 readonly string root=Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,".."));
 readonly List<Item> items=new List<Item>();readonly Dictionary<string,Bitmap> art=new Dictionary<string,Bitmap>();
 readonly Timer timer=new Timer();readonly Queue<ushort> keys=new Queue<ushort>();readonly int saveBytes;int slot=-1;ushort sequence=0;DateTime last=DateTime.UtcNow;double debt=0;
 string saveFolder="saves";
 Music music;
 string SavePath(int id){return Path.Combine(root,"PC_Preview",saveFolder,"slot"+id+".bin");}
 byte[] ReadSave(int id){try{byte[] b=File.ReadAllBytes(SavePath(id));return b.Length==saveBytes&&Engine.st_valid(b)!=0?b:null;}catch{return null;}}
 byte[] Latest(){byte[] a=ReadSave(0),b=ReadSave(1);if(a==null&&b==null)return null;int sa=a==null?0:(a[4]<<8)|a[5],sb=b==null?0:(b[4]<<8)|b[5];slot=a==null?1:0;int delta=(sb-sa)&65535;if(a!=null&&b!=null&&delta>0&&delta<32768)slot=1;byte[] best=slot==0?a:b;sequence=(ushort)((best[4]<<8)|best[5]);return best;}
 void Persist(){int request=Engine.st_requests();if((request&2)!=0)Engine.st_load(Latest());if((request&1)==0)return;
  int next=slot<0?0:1-slot;ushort seq=(ushort)(sequence+1);byte[] data=new byte[saveBytes];Engine.st_save(data,seq);
  try {Directory.CreateDirectory(Path.GetDirectoryName(SavePath(next)));using(var fs=new FileStream(SavePath(next),FileMode.Create,FileAccess.Write,FileShare.None)){fs.Write(data,0,data.Length);fs.Flush(true);}byte[] check=ReadSave(next);if(check==null||Convert.ToBase64String(data)!=Convert.ToBase64String(check))throw new IOException("Save verification failed");sequence=seq;slot=next;Engine.st_saved(1,seq);}
  catch{Engine.st_saved(0,seq);}
 }
 Bitmap Art(string kind,int index){string k=kind+"/"+index;if(!art.ContainsKey(k)){string dir=kind=="pages"?"32_Pages":kind=="tiles"?"40_Tiles":"48_HUD";string format=kind=="pages"?"D2":"D3";using(var source=new Bitmap(Path.Combine(root,"Assets",dir,index.ToString(format)+".bmp")))art[k]=new Bitmap(source);}return art[k];}
 public Preview(bool testing=false){saveBytes=Engine.st_save_bytes();if(testing)saveFolder="test_saves_"+DateTime.UtcNow.ToString("yyyyMMddHHmmssfff");Text="星辉魔塔 · 电脑试玩（同源 C 引擎）";ClientSize=new Size(1000,600);MinimumSize=new Size(816,519);StartPosition=FormStartPosition.CenterScreen;DoubleBuffered=true;KeyPreview=true;AutoScaleMode=AutoScaleMode.None;
  foreach(string line in File.ReadAllLines(Path.Combine(root,"GUI","controls.tsv"),Encoding.UTF8)){string[] a=line.Split('\t');items.Add(new Item{Key=a[0]=="key",Page=int.Parse(a[1]),X=int.Parse(a[2]),Y=int.Parse(a[3]),W=int.Parse(a[4]),H=int.Parse(a[5]),VP=ushort.Parse(a[6]),Min=int.Parse(a[7]),Max=int.Parse(a[8]),Lib=int.Parse(a[9]),Code=ushort.Parse(a[12])});}
  Engine.st_init();Engine.st_preferences(Latest());if(!testing){music=new Music(root);music.Update(Engine.st_audio(0));}
  timer.Interval=16;timer.Tick+=delegate {DateTime now=DateTime.UtcNow;debt+=Math.Min(200,(now-last).TotalMilliseconds);last=now;while(debt>=50){debt-=50;Engine.st_tick(keys.Count>0?keys.Dequeue():(ushort)0);Persist();if(music!=null)music.Update(Engine.st_audio(music.Playing));if(Engine.st_page()>=11)keys.Clear();}Invalidate();};timer.Start();
 }
 public void Render(Graphics g){g.Clear(Color.FromArgb(11,19,34));g.InterpolationMode=InterpolationMode.NearestNeighbor;g.PixelOffsetMode=PixelOffsetMode.Half;int page=Engine.st_page();g.DrawImageUnscaled(Art("pages",page),0,0);
  foreach(Item c in items)if(!c.Key&&c.Page==page){int idx=c.Min+Engine.st_vp(c.VP);if(idx<c.Min||idx>c.Max)continue;g.DrawImageUnscaled(Art(c.Lib==40?"tiles":"hud",idx),c.X,c.Y);}
 }
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);e.Graphics.Clear(Color.FromArgb(6,10,19));float s=Math.Min(ClientSize.Width/800f,ClientSize.Height/480f);e.Graphics.TranslateTransform((ClientSize.Width-800*s)/2,(ClientSize.Height-480*s)/2);e.Graphics.ScaleTransform(s,s);Render(e.Graphics);}
 void Enqueue(ushort k){if(Engine.st_page()<=10&&keys.Count<4)keys.Enqueue(k);}
 protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);float s=Math.Min(ClientSize.Width/800f,ClientSize.Height/480f);float x=(e.X-(ClientSize.Width-800*s)/2)/s,y=(e.Y-(ClientSize.Height-480*s)/2)/s;foreach(Item c in items)if(c.Key&&c.Page==Engine.st_page()&&x>=c.X&&x<c.X+c.W&&y>=c.Y&&y<c.Y+c.H){Enqueue(c.Code);break;}Focus();}
 protected override bool ProcessCmdKey(ref Message msg,Keys keyData){ushort code=0;if(Engine.st_page()==10){switch(keyData){case Keys.D0:case Keys.NumPad0:code=40;break;case Keys.D1:case Keys.NumPad1:code=41;break;case Keys.D2:case Keys.NumPad2:code=42;break;case Keys.D3:case Keys.NumPad3:code=43;break;case Keys.D4:case Keys.NumPad4:code=44;break;case Keys.D5:case Keys.NumPad5:code=45;break;case Keys.D6:case Keys.NumPad6:code=46;break;case Keys.D7:case Keys.NumPad7:code=47;break;case Keys.D8:case Keys.NumPad8:code=48;break;case Keys.D9:case Keys.NumPad9:code=49;break;case Keys.Delete:case Keys.Escape:code=50;break;case Keys.Back:code=51;break;case Keys.Enter:code=52;break;}}else{switch(keyData){case Keys.W:case Keys.Up:code=10;break;case Keys.S:case Keys.Down:code=11;break;case Keys.A:case Keys.Left:code=12;break;case Keys.D:case Keys.Right:code=13;break;case Keys.M:code=38;break;case Keys.B:code=20;break;case Keys.I:code=21;break;case Keys.F5:code=23;break;case Keys.Escape:code=Engine.st_page()==2?(ushort)22:Engine.st_page()==8?(ushort)24:(ushort)5;break;}}if(code!=0){Enqueue(code);return true;}return base.ProcessCmdKey(ref msg,keyData);}
 protected override void Dispose(bool disposing){if(disposing){timer.Stop();timer.Dispose();if(music!=null)music.Dispose();foreach(var b in art.Values)b.Dispose();}base.Dispose(disposing);}
 void Login(){for(int pass=0;pass<2;pass++){foreach(char c in "123456")Engine.st_tick((ushort)(40+c-'0'));Engine.st_tick(52);}if(Engine.st_page()!=1)throw new Exception("Default login failed");}
 void SelfTest(){timer.Stop();for(int i=0;i<60;i++)Engine.st_tick(0);Login();Engine.st_tick(1);Engine.st_tick(25);Persist();if(slot!=0)throw new Exception("First save slot failed");Engine.st_tick(13);Engine.st_tick(13);if(Engine.st_vp(0x1151)!=1)throw new Exception("Key pickup failed");Engine.st_tick(23);Persist();if(slot!=1)throw new Exception("Second save slot failed");Engine.st_init();for(int i=0;i<60;i++)Engine.st_tick(0);Login();Engine.st_tick(2);Persist();if(Engine.st_page()!=2||Engine.st_vp(0x1151)!=1)throw new Exception("Resume latest failed");byte[] bad=File.ReadAllBytes(SavePath(1));bad[10]^=1;File.WriteAllBytes(SavePath(1),bad);Engine.st_init();for(int i=0;i<60;i++)Engine.st_tick(0);Login();Engine.st_tick(2);Persist();if(Engine.st_page()!=2||Engine.st_vp(0x1151)!=0)throw new Exception("Corrupt-slot fallback failed");Engine.st_tick(22);Engine.st_tick(38);Engine.st_tick(4);Persist();if(Engine.st_page()!=11)throw new Exception("Home loading failed");for(int i=0;i<60;i++)Engine.st_tick(13);if(Engine.st_page()!=1)throw new Exception("Home target failed");Engine.st_tick(2);Persist();if(Engine.st_page()!=2||Engine.st_vp(0x1330)!=3)throw new Exception("Audio preference resume failed");using(var audioCheck=new Music(root)){}File.WriteAllText(Path.Combine(root,"Docs","pc_persistence_test.txt"),"PASS: default account/password login, 320-byte v2 alternating save slots, resume latest, corrupted newest slot falls back to previous valid save; save before home, 15-frame loading, audio preference resume, four valid PCM tracks.\r\nTest files: PC_Preview/"+saveFolder+"\r\n");}
 [STAThread] static void Main(string[] args){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);try{using(var form=new Preview(args.Length>0)){if(args.Length>0&&args[0]=="--self-test"){form.SelfTest();return;}if(args.Length==2&&args[0]=="--render-check"){form.timer.Stop();for(int i=0;i<60;i++)Engine.st_tick(0);form.Login();Engine.st_tick(1);Engine.st_tick(25);using(var b=new Bitmap(800,480)){using(Graphics g=Graphics.FromImage(b))form.Render(g);b.Save(args[1],System.Drawing.Imaging.ImageFormat.Png);}return;}Application.Run(form);}}catch(Exception e){if(args.Length>0){File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"preview_error.log"),e.ToString());Environment.ExitCode=1;}else MessageBox.Show(e.Message,"星辉魔塔",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
}
